from enum import Enum

mijournée = {1:'matin', 2:'après-midi'}

class Interest(str, Enum):
    Botany = "Botany"
    Court_fashion = "Court_fashion"
    Court_festivities = "Court_festivities"
    Court_society = "Court_society"
    Decoration_styles = "Decoration_styles"
    Diplomatic_history = "Diplomatic_history"
    Engineering_marvels = "Engineering_marvels"
    Enlightenment = "Enlightenment"
    Family = "Family"
    Food_history = "Food_history"
    Formal_gardens = "Formal_gardens"
    French_monarchy = "French_monarchy"
    Grand_Trianon = "Grand_Trianon"
    Grand_canal = "Grand_canal"
    Music = "Music"
    Painting = "Painting"
    Palace_architecture = "Palace_architecture"
    Petit_Trianon = "Petit_Trianon"
    Philosophy = "Philosophy"
    Private_apartments = "Private_apartments"
    Queen_s_Hamlet = "Queen_s_Hamlet"
    Royal_chapel = "Royal_chapel"
    Royal_life = "Royal_life"
    Scientific_history = "Scientific_history"
    Sculpture = "Sculpture"
    Symbolism_Roi_Soleil = "Symbolism_Roi_Soleil"
    Waterworks = "Waterworks"

    def __str__(self):
        return self.value

    def __repr__(self):
        return self.value

ACTIVITY_CALENDAR = [{'activity_id': 'versailles-2025-1',
  'name': 'Morning Stroll: Gardens of the Sun King',
  'start_time': '01-10-2025 09:00',
  'end_time': '01-10-2025 11:00',
  'location': 'Versailles Formal Gardens, Palace Grounds',
  'description': 'Begin your October visit with a guided walk through the stunning formal gardens designed by André Le Nôtre. Explore the geometry, symbolism, and stories behind the fountains and flower beds, while learning about the Roi Soleil’s vision for harmony between art and nature. In case of rain, the tour includes an indoor illustrated talk on Le Nôtre’s garden designs.',
  'price': 18,
  'related_interests': ['Formal_gardens',
   'Symbolism_Roi_Soleil',
   'Waterworks'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-2',
  'name': 'Gardener’s Secrets: Versailles Flora',
  'start_time': '01-10-2025 09:30',
  'end_time': '01-10-2025 11:30',
  'location': 'Versailles Gardens, Orangery Area',
  'description': 'Join Versailles’ gardeners for a behind-the-scenes look at rare plants, seasonal flowers, and the secrets of maintaining the Sun King’s gardens. Includes a demonstration of historic pruning and planting techniques.',
  'price': 18,
  'related_interests': ['Botany', 'Formal_gardens', 'Engineering_marvels'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-3',
  'name': 'Palace Architecture Masterclass',
  'start_time': '01-10-2025 10:30',
  'end_time': '01-10-2025 12:30',
  'location': 'Architectural Galleries, Château de Versailles',
  'description': 'Dive into the evolution of Versailles’ architecture. This masterclass explores construction phases, engineering innovations, and stylistic choices that transformed a hunting lodge into a symbol of absolutist power.',
  'price': 20,
  'related_interests': ['Palace_architecture',
   'Engineering_marvels',
   'Decoration_styles'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-4',
  'name': 'Royal Etiquette Workshop: Life at Court',
  'start_time': '01-10-2025 14:00',
  'end_time': '01-10-2025 16:00',
  'location': 'Hall of Mirrors, Château de Versailles',
  'description': 'Step into the shoes of a courtier! Learn the gestures, language, and strict etiquette that governed life at Versailles. This interactive workshop reveals how nobles dined, danced, and navigated the elaborate hierarchy of the court, offering participants a lively immersion in the world of Louis XIV.',
  'price': 20,
  'related_interests': ['Royal_life', 'Court_society', 'Court_fashion'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-5',
  'name': 'Sculpture & Symbolism Tour',
  'start_time': '01-10-2025 14:00',
  'end_time': '01-10-2025 16:00',
  'location': 'Palace Gardens & Sculpture Galleries',
  'description': 'From mythological figures to allegories of power, this guided tour reveals how sculptures in the gardens and palace interiors conveyed royal propaganda. Learn to read Versailles’ visual language through marble and bronze.',
  'price': 18,
  'related_interests': ['Sculpture', 'Symbolism_Roi_Soleil', 'Formal_gardens'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-6',
  'name': 'Paintings of Power: Guided Tour',
  'start_time': '01-10-2025 15:00',
  'end_time': '01-10-2025 17:00',
  'location': 'Hall of Battles, Château de Versailles',
  'description': 'A thematic tour focusing on the monumental canvases of the Hall of Battles, showing how art celebrated victories and reinforced royal authority.',
  'price': 20,
  'related_interests': ['Painting', 'French_monarchy', 'Diplomatic_history'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-7',
  'name': 'Marie-Antoinette’s Private World',
  'start_time': '01-10-2025 14:00',
  'end_time': '01-10-2025 16:00',
  'location': 'Petit Trianon & Private Apartments',
  'description': 'A special visit dedicated to the private life of Marie-Antoinette. Explore the Petit Trianon and her private apartments, while uncovering the contrast between the queen’s intimate retreats and her public image.',
  'price': 22,
  'related_interests': ['Private_apartments',
   'Petit_Trianon',
   'Court_society'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-8',
  'name': 'Night Fountains Show',
  'start_time': '01-10-2025 18:00',
  'end_time': '01-10-2025 20:00',
  'location': 'Versailles Gardens, Grand Canal Area',
  'description': 'A spectacular evening display with illuminated fountains, fireworks, and Baroque music. A theatrical tribute to the grandeur of the Roi Soleil.',
  'price': 30,
  'related_interests': ['Waterworks',
   'Court_festivities',
   'Symbolism_Roi_Soleil'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-1',
  'name': 'Morning Stroll: Gardens of the Sun King',
  'start_time': '02-10-2025 09:00',
  'end_time': '02-10-2025 11:00',
  'location': 'Versailles Formal Gardens, Palace Grounds',
  'description': 'Begin your October visit with a guided walk through the stunning formal gardens designed by André Le Nôtre. Explore the geometry, symbolism, and stories behind the fountains and flower beds, while learning about the Roi Soleil’s vision for harmony between art and nature. In case of rain, the tour includes an indoor illustrated talk on Le Nôtre’s garden designs.',
  'price': 18,
  'related_interests': ['Formal_gardens',
   'Symbolism_Roi_Soleil',
   'Waterworks'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-9',
  'name': 'Chapel Harmonies: Morning Organ Recital',
  'start_time': '02-10-2025 10:00',
  'end_time': '02-10-2025 11:00',
  'location': 'Royal Chapel, Château de Versailles',
  'description': 'Awaken your senses with the majestic sounds of the organ inside the Royal Chapel. Performed by resident musicians, the recital features works by French Baroque masters, echoing the very music heard during Louis XIV’s reign.',
  'price': 15,
  'related_interests': ['Music', 'Royal_chapel', 'Court_festivities'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-7',
  'name': 'Marie-Antoinette’s Private World',
  'start_time': '02-10-2025 14:00',
  'end_time': '02-10-2025 16:00',
  'location': 'Petit Trianon & Private Apartments',
  'description': 'A special visit dedicated to the private life of Marie-Antoinette. Explore the Petit Trianon and her private apartments, while uncovering the contrast between the queen’s intimate retreats and her public image.',
  'price': 22,
  'related_interests': ['Private_apartments',
   'Petit_Trianon',
   'Court_society'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-10',
  'name': 'Art & Politics: The French Monarchy in Paintings',
  'start_time': '02-10-2025 14:30',
  'end_time': '02-10-2025 16:30',
  'location': 'The State Apartments, Château de Versailles',
  'description': 'A thematic gallery tour focusing on Versailles’ rich collection of paintings. Discover how the monarchy used portraiture and historical canvases to shape political identity and authority, from Louis XIV to the Revolution.',
  'price': 20,
  'related_interests': ['Painting', 'French_monarchy', 'Diplomatic_history'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-5',
  'name': 'Sculpture & Symbolism Tour',
  'start_time': '02-10-2025 14:00',
  'end_time': '02-10-2025 16:00',
  'location': 'Palace Gardens & Sculpture Galleries',
  'description': 'From mythological figures to allegories of power, this guided tour reveals how sculptures in the gardens and palace interiors conveyed royal propaganda. Learn to read Versailles’ visual language through marble and bronze.',
  'price': 18,
  'related_interests': ['Sculpture', 'Symbolism_Roi_Soleil', 'Formal_gardens'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-2',
  'name': 'Gardener’s Secrets: Versailles Flora',
  'start_time': '03-10-2025 09:30',
  'end_time': '03-10-2025 11:30',
  'location': 'Versailles Gardens, Orangery Area',
  'description': 'Join Versailles’ gardeners for a behind-the-scenes look at rare plants, seasonal flowers, and the secrets of maintaining the Sun King’s gardens. Includes a demonstration of historic pruning and planting techniques.',
  'price': 18,
  'related_interests': ['Botany', 'Formal_gardens', 'Engineering_marvels'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-3',
  'name': 'Palace Architecture Masterclass',
  'start_time': '03-10-2025 10:30',
  'end_time': '03-10-2025 12:30',
  'location': 'Architectural Galleries, Château de Versailles',
  'description': 'Dive into the evolution of Versailles’ architecture. This masterclass explores construction phases, engineering innovations, and stylistic choices that transformed a hunting lodge into a symbol of absolutist power.',
  'price': 20,
  'related_interests': ['Palace_architecture',
   'Engineering_marvels',
   'Decoration_styles'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-11',
  'name': 'Fountain Spectacle: Water, Light, and Music',
  'start_time': '03-10-2025 17:00',
  'end_time': '03-10-2025 19:00',
  'location': 'Grand Canal and Fountains, Palace Gardens',
  'description': 'Experience Versailles’ grand fountains in action, accompanied by a curated program of Baroque music. As the sun sets, water, sound, and light transform the gardens into a theatrical celebration of power and beauty. Outdoor event; in case of rain, replaced with an indoor multimedia lecture on the engineering of Versailles’ waterworks.',
  'price': 22,
  'related_interests': ['Waterworks',
   'Music',
   'Symbolism_Roi_Soleil',
   'Engineering_marvels'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-1',
  'name': 'Morning Stroll: Gardens of the Sun King',
  'start_time': '03-10-2025 09:00',
  'end_time': '03-10-2025 11:00',
  'location': 'Versailles Formal Gardens, Palace Grounds',
  'description': 'Begin your October visit with a guided walk through the stunning formal gardens designed by André Le Nôtre. Explore the geometry, symbolism, and stories behind the fountains and flower beds, while learning about the Roi Soleil’s vision for harmony between art and nature. In case of rain, the tour includes an indoor illustrated talk on Le Nôtre’s garden designs.',
  'price': 18,
  'related_interests': ['Formal_gardens',
   'Symbolism_Roi_Soleil',
   'Waterworks'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-12',
  'name': 'Engineering Versailles’ Water System',
  'start_time': '03-10-2025 14:00',
  'end_time': '03-10-2025 16:00',
  'location': 'Waterworks Pavilion & Gardens',
  'description': 'A special program on the grand hydraulic system that powered Versailles’ fountains. Includes a visit to the pumping station and garden demonstration.',
  'price': 20,
  'related_interests': ['Engineering_marvels',
   'Waterworks',
   'Symbolism_Roi_Soleil'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-7',
  'name': 'Marie-Antoinette’s Private World',
  'start_time': '03-10-2025 14:00',
  'end_time': '03-10-2025 16:00',
  'location': 'Petit Trianon & Private Apartments',
  'description': 'A special visit dedicated to the private life of Marie-Antoinette. Explore the Petit Trianon and her private apartments, while uncovering the contrast between the queen’s intimate retreats and her public image.',
  'price': 22,
  'related_interests': ['Private_apartments',
   'Petit_Trianon',
   'Court_society'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-13',
  'name': 'Botanical Afternoon: The Queen’s Hamlet',
  'start_time': '03-10-2025 14:30',
  'end_time': '03-10-2025 16:30',
  'location': 'Queen’s Hamlet, Petit Trianon Grounds',
  'description': 'A peaceful afternoon dedicated to exploring Marie-Antoinette’s pastoral retreat. Learn about 18th-century botany, rustic garden design, and the queen’s fascination with rural life, blending fantasy and practicality.',
  'price': 18,
  'related_interests': ['Botany', 'Queen_s_Hamlet', 'Court_society'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-14',
  'name': 'Botanical Morning: The Queen’s Hamlet',
  'start_time': '04-10-2025 09:30',
  'end_time': '04-10-2025 11:30',
  'location': 'Queen’s Hamlet, Petit Trianon Grounds',
  'description': 'A peaceful morning dedicated to exploring Marie-Antoinette’s pastoral retreat. Learn about 18th-century botany, rustic garden design, and the queen’s fascination with rural life, blending fantasy and practicality.',
  'price': 18,
  'related_interests': ['Botany', 'Queen_s_Hamlet', 'Court_society'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-9',
  'name': 'Chapel Harmonies: Morning Organ Recital',
  'start_time': '04-10-2025 10:00',
  'end_time': '04-10-2025 11:00',
  'location': 'Royal Chapel, Château de Versailles',
  'description': 'Awaken your senses with the majestic sounds of the organ inside the Royal Chapel. Performed by resident musicians, the recital features works by French Baroque masters, echoing the very music heard during Louis XIV’s reign.',
  'price': 15,
  'related_interests': ['Music', 'Royal_chapel', 'Court_festivities'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-6',
  'name': 'Paintings of Power: Guided Tour',
  'start_time': '04-10-2025 15:00',
  'end_time': '04-10-2025 17:00',
  'location': 'Hall of Battles, Château de Versailles',
  'description': 'A thematic tour focusing on the monumental canvases of the Hall of Battles, showing how art celebrated victories and reinforced royal authority.',
  'price': 20,
  'related_interests': ['Painting', 'French_monarchy', 'Diplomatic_history'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-7',
  'name': 'Marie-Antoinette’s Private World',
  'start_time': '04-10-2025 14:00',
  'end_time': '04-10-2025 16:00',
  'location': 'Petit Trianon & Private Apartments',
  'description': 'A special visit dedicated to the private life of Marie-Antoinette. Explore the Petit Trianon and her private apartments, while uncovering the contrast between the queen’s intimate retreats and her public image.',
  'price': 22,
  'related_interests': ['Private_apartments',
   'Petit_Trianon',
   'Court_society'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-13',
  'name': 'Botanical Afternoon: The Queen’s Hamlet',
  'start_time': '04-10-2025 14:30',
  'end_time': '04-10-2025 16:30',
  'location': 'Queen’s Hamlet, Petit Trianon Grounds',
  'description': 'A peaceful afternoon dedicated to exploring Marie-Antoinette’s pastoral retreat. Learn about 18th-century botany, rustic garden design, and the queen’s fascination with rural life, blending fantasy and practicality.',
  'price': 18,
  'related_interests': ['Botany', 'Queen_s_Hamlet', 'Court_society'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-5',
  'name': 'Sculpture & Symbolism Tour',
  'start_time': '04-10-2025 14:00',
  'end_time': '04-10-2025 16:00',
  'location': 'Palace Gardens & Sculpture Galleries',
  'description': 'From mythological figures to allegories of power, this guided tour reveals how sculptures in the gardens and palace interiors conveyed royal propaganda. Learn to read Versailles’ visual language through marble and bronze.',
  'price': 18,
  'related_interests': ['Sculpture', 'Symbolism_Roi_Soleil', 'Formal_gardens'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-15',
  'name': 'Twilight Chamber Concert at the Grand Trianon',
  'start_time': '04-10-2025 18:30',
  'end_time': '04-10-2025 20:00',
  'location': 'Grand Trianon, Château de Versailles',
  'description': 'Enjoy an intimate evening of chamber music in the elegant marble setting of the Grand Trianon. The program features works performed in the 17th and 18th centuries for royal gatherings, highlighting the palace’s enduring connection to art and music.',
  'price': 25,
  'related_interests': ['Music', 'Grand_Trianon', 'Court_festivities'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-1',
  'name': 'Morning Stroll: Gardens of the Sun King',
  'start_time': '05-10-2025 09:00',
  'end_time': '05-10-2025 11:00',
  'location': 'Versailles Formal Gardens, Palace Grounds',
  'description': 'Begin your October visit with a guided walk through the stunning formal gardens designed by André Le Nôtre. Explore the geometry, symbolism, and stories behind the fountains and flower beds, while learning about the Roi Soleil’s vision for harmony between art and nature. In case of rain, the tour includes an indoor illustrated talk on Le Nôtre’s garden designs.',
  'price': 18,
  'related_interests': ['Formal_gardens',
   'Symbolism_Roi_Soleil',
   'Waterworks'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-16',
  'name': 'Family Treasure Hunt: Secrets of Versailles',
  'start_time': '05-10-2025 10:00',
  'end_time': '05-10-2025 12:00',
  'location': 'Palace Grounds and Gardens',
  'description': 'Families are invited to a playful treasure hunt that combines history, puzzles, and exploration. Follow clues through the gardens and palace spaces, uncovering the hidden stories of kings, queens, and courtiers along the way.',
  'price': 12,
  'related_interests': ['Court_society',
   'Formal_gardens',
   'Palace_architecture'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-7',
  'name': 'Marie-Antoinette’s Private World',
  'start_time': '05-10-2025 14:00',
  'end_time': '05-10-2025 16:00',
  'location': 'Petit Trianon & Private Apartments',
  'description': 'A special visit dedicated to the private life of Marie-Antoinette. Explore the Petit Trianon and her private apartments, while uncovering the contrast between the queen’s intimate retreats and her public image.',
  'price': 22,
  'related_interests': ['Private_apartments',
   'Petit_Trianon',
   'Court_society'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-17',
  'name': 'Evening Lecture: Versailles and Diplomacy',
  'start_time': '05-10-2025 17:00',
  'end_time': '05-10-2025 18:30',
  'location': 'Palace Auditorium, Château de Versailles',
  'description': 'A scholarly lecture exploring how Versailles became the stage of European diplomacy. From treaties to royal receptions, discover the palace’s role in shaping international relations and ceremonial politics.',
  'price': 15,
  'related_interests': ['Diplomatic_history', 'French_monarchy', 'Royal_life'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-8',
  'name': 'Night Fountains Show',
  'start_time': '05-10-2025 18:00',
  'end_time': '05-10-2025 20:00',
  'location': 'Versailles Gardens, Grand Canal Area',
  'description': 'A spectacular evening display with illuminated fountains, fireworks, and Baroque music. A theatrical tribute to the grandeur of the Roi Soleil.',
  'price': 30,
  'related_interests': ['Waterworks',
   'Court_festivities',
   'Symbolism_Roi_Soleil'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-1',
  'name': 'Morning Stroll: Gardens of the Sun King',
  'start_time': '06-10-2025 09:00',
  'end_time': '06-10-2025 11:00',
  'location': 'Versailles Formal Gardens, Palace Grounds',
  'description': 'Begin your October visit with a guided walk through the stunning formal gardens designed by André Le Nôtre. Explore the geometry, symbolism, and stories behind the fountains and flower beds, while learning about the Roi Soleil’s vision for harmony between art and nature. In case of rain, the tour includes an indoor illustrated talk on Le Nôtre’s garden designs.',
  'price': 18,
  'related_interests': ['Formal_gardens',
   'Symbolism_Roi_Soleil',
   'Waterworks'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-9',
  'name': 'Chapel Harmonies: Morning Organ Recital',
  'start_time': '06-10-2025 10:00',
  'end_time': '06-10-2025 11:00',
  'location': 'Royal Chapel, Château de Versailles',
  'description': 'Awaken your senses with the majestic sounds of the organ inside the Royal Chapel. Performed by resident musicians, the recital features works by French Baroque masters, echoing the very music heard during Louis XIV’s reign.',
  'price': 15,
  'related_interests': ['Music', 'Royal_chapel', 'Court_festivities'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-13',
  'name': 'Botanical Afternoon: The Queen’s Hamlet',
  'start_time': '06-10-2025 14:30',
  'end_time': '06-10-2025 16:30',
  'location': 'Queen’s Hamlet, Petit Trianon Grounds',
  'description': 'A peaceful afternoon dedicated to exploring Marie-Antoinette’s pastoral retreat. Learn about 18th-century botany, rustic garden design, and the queen’s fascination with rural life, blending fantasy and practicality.',
  'price': 18,
  'related_interests': ['Botany', 'Queen_s_Hamlet', 'Court_society'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-5',
  'name': 'Sculpture & Symbolism Tour',
  'start_time': '06-10-2025 14:00',
  'end_time': '06-10-2025 16:00',
  'location': 'Palace Gardens & Sculpture Galleries',
  'description': 'From mythological figures to allegories of power, this guided tour reveals how sculptures in the gardens and palace interiors conveyed royal propaganda. Learn to read Versailles’ visual language through marble and bronze.',
  'price': 18,
  'related_interests': ['Sculpture', 'Symbolism_Roi_Soleil', 'Formal_gardens'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-18',
  'name': 'Twilight by the Grand Canal: Boat & Music',
  'start_time': '06-10-2025 18:00',
  'end_time': '06-10-2025 20:00',
  'location': 'Grand Canal, Palace Grounds',
  'description': 'Recreate the festive evenings of the court with a twilight boat ride on the Grand Canal accompanied by live music. Participants will enjoy refreshments and a short talk on the grand spectacles of the Roi Soleil.',
  'price': 30,
  'related_interests': ['Grand_canal', 'Court_festivities', 'Music'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-1',
  'name': 'Morning Stroll: Gardens of the Sun King',
  'start_time': '07-10-2025 09:00',
  'end_time': '07-10-2025 11:00',
  'location': 'Versailles Formal Gardens, Palace Grounds',
  'description': 'Begin your October visit with a guided walk through the stunning formal gardens designed by André Le Nôtre. Explore the geometry, symbolism, and stories behind the fountains and flower beds, while learning about the Roi Soleil’s vision for harmony between art and nature. In case of rain, the tour includes an indoor illustrated talk on Le Nôtre’s garden designs.',
  'price': 18,
  'related_interests': ['Formal_gardens',
   'Symbolism_Roi_Soleil',
   'Waterworks'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-3',
  'name': 'Palace Architecture Masterclass',
  'start_time': '07-10-2025 10:30',
  'end_time': '07-10-2025 12:30',
  'location': 'Architectural Galleries, Château de Versailles',
  'description': 'Dive into the evolution of Versailles’ architecture. This masterclass explores construction phases, engineering innovations, and stylistic choices that transformed a hunting lodge into a symbol of absolutist power.',
  'price': 20,
  'related_interests': ['Palace_architecture',
   'Engineering_marvels',
   'Decoration_styles'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-12',
  'name': 'Engineering Versailles’ Water System',
  'start_time': '07-10-2025 14:00',
  'end_time': '07-10-2025 16:00',
  'location': 'Waterworks Pavilion & Gardens',
  'description': 'A special program on the grand hydraulic system that powered Versailles’ fountains. Includes a visit to the pumping station and garden demonstration.',
  'price': 20,
  'related_interests': ['Engineering_marvels',
   'Waterworks',
   'Symbolism_Roi_Soleil'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-13',
  'name': 'Botanical Afternoon: The Queen’s Hamlet',
  'start_time': '07-10-2025 14:30',
  'end_time': '07-10-2025 16:30',
  'location': 'Queen’s Hamlet, Petit Trianon Grounds',
  'description': 'A peaceful afternoon dedicated to exploring Marie-Antoinette’s pastoral retreat. Learn about 18th-century botany, rustic garden design, and the queen’s fascination with rural life, blending fantasy and practicality.',
  'price': 18,
  'related_interests': ['Botany', 'Queen_s_Hamlet', 'Court_society'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-19',
  'name': 'Evening Theater Revival: Court Performances',
  'start_time': '07-10-2025 19:00',
  'end_time': '07-10-2025 21:00',
  'location': 'Royal Opera House, Château de Versailles',
  'description': 'Step back into the 18th century with a revival of theatrical works once performed for the court. This evening event blends drama, music, and dance in the ornate Royal Opera House, echoing the splendor of Versailles festivities.',
  'price': 28,
  'related_interests': ['Music', 'Court_festivities', 'Royal_life'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-9',
  'name': 'Chapel Harmonies: Morning Organ Recital',
  'start_time': '08-10-2025 10:00',
  'end_time': '08-10-2025 11:00',
  'location': 'Royal Chapel, Château de Versailles',
  'description': 'Awaken your senses with the majestic sounds of the organ inside the Royal Chapel. Performed by resident musicians, the recital features works by French Baroque masters, echoing the very music heard during Louis XIV’s reign.',
  'price': 15,
  'related_interests': ['Music', 'Royal_chapel', 'Court_festivities'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-14',
  'name': 'Botanical Morning: The Queen’s Hamlet',
  'start_time': '08-10-2025 09:30',
  'end_time': '08-10-2025 11:30',
  'location': 'Queen’s Hamlet, Petit Trianon Grounds',
  'description': 'A peaceful morning dedicated to exploring Marie-Antoinette’s pastoral retreat. Learn about 18th-century botany, rustic garden design, and the queen’s fascination with rural life, blending fantasy and practicality.',
  'price': 18,
  'related_interests': ['Botany', 'Queen_s_Hamlet', 'Court_society'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-7',
  'name': 'Marie-Antoinette’s Private World',
  'start_time': '08-10-2025 14:00',
  'end_time': '08-10-2025 16:00',
  'location': 'Petit Trianon & Private Apartments',
  'description': 'A special visit dedicated to the private life of Marie-Antoinette. Explore the Petit Trianon and her private apartments, while uncovering the contrast between the queen’s intimate retreats and her public image.',
  'price': 22,
  'related_interests': ['Private_apartments',
   'Petit_Trianon',
   'Court_society'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-5',
  'name': 'Sculpture & Symbolism Tour',
  'start_time': '08-10-2025 14:00',
  'end_time': '08-10-2025 16:00',
  'location': 'Palace Gardens & Sculpture Galleries',
  'description': 'From mythological figures to allegories of power, this guided tour reveals how sculptures in the gardens and palace interiors conveyed royal propaganda. Learn to read Versailles’ visual language through marble and bronze.',
  'price': 18,
  'related_interests': ['Sculpture', 'Symbolism_Roi_Soleil', 'Formal_gardens'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-3',
  'name': 'Palace Architecture Masterclass',
  'start_time': '09-10-2025 10:30',
  'end_time': '09-10-2025 12:30',
  'location': 'Architectural Galleries, Château de Versailles',
  'description': 'Dive into the evolution of Versailles’ architecture. This masterclass explores construction phases, engineering innovations, and stylistic choices that transformed a hunting lodge into a symbol of absolutist power.',
  'price': 20,
  'related_interests': ['Palace_architecture',
   'Engineering_marvels',
   'Decoration_styles'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-20',
  'name': 'Court Fashion Through the Ages',
  'start_time': '09-10-2025 15:00',
  'end_time': '09-10-2025 17:00',
  'location': 'Costume Exhibition Hall, Château de Versailles',
  'description': 'From powdered wigs to extravagant gowns, discover the evolution of court fashion at Versailles. This event includes a guided exhibition tour and a demonstration of how these elaborate outfits were worn and maintained.',
  'price': 18,
  'related_interests': ['Court_fashion', 'Royal_life', 'Decoration_styles'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-8',
  'name': 'Night Fountains Show',
  'start_time': '09-10-2025 18:00',
  'end_time': '09-10-2025 20:00',
  'location': 'Versailles Gardens, Grand Canal Area',
  'description': 'A spectacular evening display with illuminated fountains, fireworks, and Baroque music. A theatrical tribute to the grandeur of the Roi Soleil.',
  'price': 30,
  'related_interests': ['Waterworks',
   'Court_festivities',
   'Symbolism_Roi_Soleil'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-2',
  'name': 'Gardener’s Secrets: Versailles Flora',
  'start_time': '10-10-2025 09:30',
  'end_time': '10-10-2025 11:30',
  'location': 'Versailles Gardens, Orangery Area',
  'description': 'Join Versailles’ gardeners for a behind-the-scenes look at rare plants, seasonal flowers, and the secrets of maintaining the Sun King’s gardens. Includes a demonstration of historic pruning and planting techniques.',
  'price': 18,
  'related_interests': ['Botany', 'Formal_gardens', 'Engineering_marvels'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-14',
  'name': 'Botanical Morning: The Queen’s Hamlet',
  'start_time': '10-10-2025 09:30',
  'end_time': '10-10-2025 11:30',
  'location': 'Queen’s Hamlet, Petit Trianon Grounds',
  'description': 'A peaceful morning dedicated to exploring Marie-Antoinette’s pastoral retreat. Learn about 18th-century botany, rustic garden design, and the queen’s fascination with rural life, blending fantasy and practicality.',
  'price': 18,
  'related_interests': ['Botany', 'Queen_s_Hamlet', 'Court_society'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-21',
  'name': 'Gardens as Theater: Guided Walk',
  'start_time': '10-10-2025 14:00',
  'end_time': '10-10-2025 16:00',
  'location': 'Grand Perspective & Garden Bosquets',
  'description': 'A guided walk exploring the gardens as a stage for power and spectacle. Learn how pathways, fountains, and groves were designed as theatrical backdrops for royal festivities.',
  'price': 20,
  'related_interests': ['Formal_gardens',
   'Court_festivities',
   'Symbolism_Roi_Soleil'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-22',
  'name': 'Masquerade Ball Reimagined',
  'start_time': '10-10-2025 19:00',
  'end_time': '10-10-2025 21:00',
  'location': 'Hall of Mirrors, Château de Versailles',
  'description': 'An immersive evening experience recreating the masked balls of the 18th century. Guests are invited to wear provided masks, enjoy period dance demonstrations, and learn about courtly entertainments.',
  'price': 32,
  'related_interests': ['Court_festivities', 'Court_society', 'Music'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-23',
  'name': 'Royal Children at Play: Family Workshop',
  'start_time': '11-10-2025 10:00',
  'end_time': '11-10-2025 12:00',
  'location': 'Children’s Apartments, Château de Versailles',
  'description': 'Discover the daily lives of royal children through games, toys, and interactive stories. A family-friendly workshop designed for younger visitors.',
  'price': 12,
  'related_interests': ['Royal_life', 'Court_society', 'Family'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-24',
  'name': 'Royal Inventors: Science at Court',
  'start_time': '11-10-2025 14:30',
  'end_time': '11-10-2025 16:30',
  'location': 'Science Exhibition Hall, Château de Versailles',
  'description': 'Learn how inventions, experiments, and scientific curiosity shaped life at court. This guided session highlights astronomical instruments, hydraulics, and medical practices from the period.',
  'price': 18,
  'related_interests': ['Engineering_marvels',
   'Court_society',
   'Scientific_history'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-25',
  'name': 'Chamber Music with Candles',
  'start_time': '11-10-2025 18:30',
  'end_time': '11-10-2025 20:00',
  'location': 'Salon de Musique, Château de Versailles',
  'description': 'An intimate candlelit concert of chamber works by French Baroque composers. The atmosphere recreates the cozy musical evenings once enjoyed by courtiers.',
  'price': 25,
  'related_interests': ['Music', 'Court_festivities', 'Royal_life'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-6',
  'name': 'Paintings of Power: Guided Tour',
  'start_time': '12-10-2025 15:00',
  'end_time': '12-10-2025 17:00',
  'location': 'Hall of Battles, Château de Versailles',
  'description': 'A thematic tour focusing on the monumental canvases of the Hall of Battles, showing how art celebrated victories and reinforced royal authority.',
  'price': 20,
  'related_interests': ['Painting', 'French_monarchy', 'Diplomatic_history'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-26',
  'name': 'Evening Garden Walk with Lanterns',
  'start_time': '12-10-2025 17:30',
  'end_time': '12-10-2025 19:00',
  'location': 'Palace Gardens, Versailles Grounds',
  'description': 'As twilight falls, explore the illuminated gardens with lanterns in hand. Guides share legends and hidden stories of the groves.',
  'price': 18,
  'related_interests': ['Formal_gardens',
   'Court_society',
   'Symbolism_Roi_Soleil'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-27',
  'name': 'Sun King’s Hunting Grounds Walk',
  'start_time': '13-10-2025 09:00',
  'end_time': '13-10-2025 11:00',
  'location': 'Versailles Parklands, Hunting Forest',
  'description': 'Trace the history of Versailles as a royal hunting lodge. This walk explores the forest paths, hunting pavilions, and the symbolic role of the chase at court.',
  'price': 16,
  'related_interests': ['Royal_life', 'Court_society', 'Palace_architecture'],
  'setting': 'outdoor'},
 {'activity_id': 'versailles-2025-12',
  'name': 'Engineering Versailles’ Water System',
  'start_time': '13-10-2025 14:00',
  'end_time': '13-10-2025 16:00',
  'location': 'Waterworks Pavilion & Gardens',
  'description': 'A special program on the grand hydraulic system that powered Versailles’ fountains. Includes a visit to the pumping station and garden demonstration.',
  'price': 20,
  'related_interests': ['Engineering_marvels',
   'Waterworks',
   'Symbolism_Roi_Soleil'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-28',
  'name': 'Opera Arias at the Royal Opera',
  'start_time': '13-10-2025 19:00',
  'end_time': '13-10-2025 20:30',
  'location': 'Royal Opera House, Château de Versailles',
  'description': 'A concert of French and Italian Baroque arias performed in the Royal Opera House, echoing the repertoire of Versailles’ golden age.',
  'price': 28,
  'related_interests': ['Music', 'Court_festivities', 'French_monarchy'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-29',
  'name': 'Morning Motets in the Chapel',
  'start_time': '14-10-2025 10:00',
  'end_time': '14-10-2025 11:00',
  'location': 'Royal Chapel, Château de Versailles',
  'description': 'Experience sacred music with a program of motets performed by choir and organ in the Royal Chapel, as in the time of Louis XIV.',
  'price': 15,
  'related_interests': ['Music', 'Royal_chapel', 'Court_festivities'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-30',
  'name': 'Tapestry Workshop Visit',
  'start_time': '14-10-2025 14:30',
  'end_time': '14-10-2025 16:30',
  'location': 'Gobelin Tapestry Hall, Château de Versailles',
  'description': 'Guided visit to the tapestry collections and conservation workshops. Learn about weaving techniques and the role of tapestries in courtly interiors.',
  'price': 18,
  'related_interests': ['Decoration_styles',
   'Court_society',
   'French_monarchy'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-8',
  'name': 'Night Fountains Show',
  'start_time': '14-10-2025 18:00',
  'end_time': '14-10-2025 20:00',
  'location': 'Versailles Gardens, Grand Canal Area',
  'description': 'A spectacular evening display with illuminated fountains, fireworks, and Baroque music. A theatrical tribute to the grandeur of the Roi Soleil.',
  'price': 30,
  'related_interests': ['Waterworks',
   'Court_festivities',
   'Symbolism_Roi_Soleil'],
  'setting': 'mixed'},
 {'activity_id': 'versailles-2025-31',
  'name': 'Behind the Kitchens: Food Supply of Versailles',
  'start_time': '15-10-2025 09:30',
  'end_time': '15-10-2025 11:30',
  'location': 'Royal Kitchens, Château de Versailles',
  'description': 'Explore the logistics of feeding the court of Versailles. Guided visit of the historic kitchens, with displays on food storage, menus, and lavish banquets.',
  'price': 18,
  'related_interests': ['Court_society', 'Royal_life', 'Food_history'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-32',
  'name': 'Philosophy Salon: Enlightenment at Versailles',
  'start_time': '15-10-2025 14:00',
  'end_time': '15-10-2025 16:00',
  'location': 'Salon de Philosophie, Château de Versailles',
  'description': 'A living history experience recreating the intellectual salons of the 18th century. Participants discuss themes of Enlightenment thought with guides in period costume.',
  'price': 16,
  'related_interests': ['Philosophy', 'Court_society', 'Enlightenment'],
  'setting': 'indoor'},
 {'activity_id': 'versailles-2025-33',
  'name': 'Royal Correspondence: Letters & Gossip',
  'start_time': '15-10-2025 19:00',
  'end_time': '15-10-2025 20:30',
  'location': 'Palace Auditorium, Château de Versailles',
  'description': 'Evening lecture-performance exploring private letters, gossip, and diplomacy at Versailles. Actors read excerpts while historians provide context.',
  'price': 15,
  'related_interests': ['Royal_life', 'Court_society', 'Diplomatic_history'],
  'setting': 'indoor'}]


WINDDIRS = ['Nord','Nord-Nord-Est','Nord-Est','Est-Nord-Est','Est','Est-Sud-Est','Sud-Est','Sud-Sud-Est','Sud','Sud-Sud-Ouest','Sud-Ouest','Ouest-Sud-Ouest','Ouest','Ouest-Nord-Ouest','Nord-Ouest','Nord-Nord-Ouest','Nord']
mijournée = {1:'matin', 2:'après-midi'}
WEATHER = {
	0: "Soleil",
	1: "Peu nuageux",
	2: "Ciel voilé",
	3: "Nuageux",
	4: "Très nuageux",
	5: "Couvert",
	6: "Brouillard",
	7: "Brouillard givrant",
	10: "Pluie faible",
	11: "Pluie modérée",
	12: "Pluie forte",
	13: "Pluie faible verglaçante",
	14: "Pluie modérée verglaçante",
	15: "Pluie forte verglaçante",
	16: "Bruine",
	20: "Neige faible",
	21: "Neige modérée",
	22: "Neige forte",
	30: "Pluie et neige mêlées faibles",
	31: "Pluie et neige mêlées modérées",
	32: "Pluie et neige mêlées fortes",
	40: "Averses de pluie locales et faibles",
	41: "Averses de pluie locales",
	42: "Averses locales et fortes",
	43: "Averses de pluie faibles",
	44: "Averses de pluie",
	45: "Averses de pluie fortes",
	46: "Averses de pluie faibles et fréquentes",
	47: "Averses de pluie fréquentes",
	48: "Averses de pluie fortes et fréquentes",
	60: "Averses de neige localisées et faibles",
	61: "Averses de neige localisées",
	62: "Averses de neige localisées et fortes",
	63: "Averses de neige faibles",
	64: "Averses de neige",
	65: "Averses de neige fortes",
	66: "Averses de neige faibles et fréquentes",
	67: "Averses de neige fréquentes",
	68: "Averses de neige fortes et fréquentes",
	70: "Averses de pluie et neige mêlées localisées et faibles",
	71: "Averses de pluie et neige mêlées localisées",
	72: "Averses de pluie et neige mêlées localisées et fortes",
	73: "Averses de pluie et neige mêlées faibles",
	74: "Averses de pluie et neige mêlées",
	75: "Averses de pluie et neige mêlées fortes",
	76: "Averses de pluie et neige mêlées faibles et nombreuses",
	77: "Averses de pluie et neige mêlées fréquentes",
	78: "Averses de pluie et neige mêlées fortes et fréquentes",
	100: "Orages faibles et locaux",
	101: "Orages locaux",
	102: "Orages fort et locaux",
	103: "Orages faibles",
	104: "Orages",
	105: "Orages forts",
	106: "Orages faibles et fréquents",
	107: "Orages fréquents",
	108: "Orages forts et fréquents",
	120: "Orages faibles et locaux de neige ou grésil",
	121: "Orages locaux de neige ou grésil",
	122: "Orages locaux de neige ou grésil",
	123: "Orages faibles de neige ou grésil",
	124: "Orages de neige ou grésil",
	125: "Orages de neige ou grésil",
	126: "Orages faibles et fréquents de neige ou grésil",
	127: "Orages fréquents de neige ou grésil",
	128: "Orages fréquents de neige ou grésil",
	130: "Orages faibles et locaux de pluie et neige mêlées ou grésil",
	131: "Orages locaux de pluie et neige mêlées ou grésil",
	132: "Orages fort et locaux de pluie et neige mêlées ou grésil",
	133: "Orages faibles de pluie et neige mêlées ou grésil",
	134: "Orages de pluie et neige mêlées ou grésil",
	135: "Orages forts de pluie et neige mêlées ou grésil",
	136: "Orages faibles et fréquents de pluie et neige mêlées ou grésil",
	137: "Orages fréquents de pluie et neige mêlées ou grésil",
	138: "Orages forts et fréquents de pluie et neige mêlées ou grésil",
	140: "Pluies orageuses",
	141: "Pluie et neige mêlées à caractère orageux",
	142: "Neige à caractère orageux",
	210: "Pluie faible intermittente",
	211: "Pluie modérée intermittente",
	212: "Pluie forte intermittente",
	220: "Neige faible intermittente",
	221: "Neige modérée intermittente",
	222: "Neige forte intermittente",
	230: "Pluie et neige mêlées",
	231: "Pluie et neige mêlées",
	232: "Pluie et neige mêlées",
	235: "Averses de grêle",
}


tips = [

"""TIPS GENERAUX:
Pour les billets Passeport dont l’entrée du château est à 15h ou audelà, conseiller de voir le Domaine de Trianon avant, avec visite des
jardins le matin, visite de Trianon dès midi, et Château à partir de l‘heure indiquée sur le billet.
Pour les billets Passeport avec entrée entre 12h30 et 14h30, visiter les jardins le matin, puis le Château, et le Domaine de Trianon en fin
d’après-midi (dernier accès à 17h45).
Bien tenir compte des horaires d’ouvertures, de fermetures et des horaires de dernier accès :
- Haute saison : 1er avril - 30 octobre
- Basse saison : 1er Novembre - 31 Mars
Prévoir de bonnes chaussures : les distances sont importantes, surtout quand on va à Trianon ou dans les jardins.
Les jardins, le Trianon et le parc valent le détour : il est conseillé de consacrer du temps à l’ensemble du domaine.
Il est recommandé d’apporter des écouteurs pour profiter au mieux de l’audioguide de l’appli smartphone,
d’autant plus en extérieur dans les jardins

Encourager les visiteurs au téléchargement gratuit de l’appli en amont de la visite (lancer le chargement des parcours audio
avant d’arriver sur place car les temps de chargement peuvent être longs sur place (pas de wifi)).
Encourager quand c’est possible et pertinent une visite guidée ou une activité famille.
Réserver les visites guidées à l’avance de manière à avoir du choix, car souvent complet le jour J.
Arriver en avance pour les visites guidées.
Prendre la carte d’abonnement “Un an à Versailles” si on pense venir 2 fois ou plus dans l’année.

Petit train :
à encourager pour la visite du Trianon.
possibilité de descendre/monter à chaque arrêt.
À Trianon, les billets aller-retour ont la priorité sur les simples retours.
Paiement CB possible directement auprès des conducteurs.
Premier départ à 11h10.
Si le budget n’est pas un problème pour vous, optez pour les voiturettes électriques, qui vous permettront de visiter le domaine à votre rythme !

Informez-vous sur les éventuelles conditions de gratuité des activités et visites.
Possibilité de prêt de fauteuil roulant au Château uniquement.
Gratuités et dispositifs spécifiques pour les personnes qui ont un handicap (sur justificatif).
Faire la promo des expositions temporaires, surtout pour les franciliens / français.
Il y a également 3 espaces gratuits ouverts l’après-midi : la salle du jeu de paume du mardi au dimanche, et les écuries uniquement les week-ends.
Les poussettes sont autorisées dans le Château, il n’y a pas de consignes mais des casiers.
Les chiens et les vélos ne sont autorisés que dans le Parc.
Le billet Passeport est valable pour une entrée dans les jardins, par la Cour d’Honneur du château ou les grilles de la Petite Venise, de la Ménagerie, de Neptune ou du Dragon.
Les galeries des Carrosses, des Sculptures et Moulages, ainsi que la salle du Jeu de Paume sont gratuites quand elles sont ouvertes. Ce sont des visites originales, moins connues et
adaptées notamment aux familles, sans réservation préalable

TIPS CONDITIONNELS:
Attention, quand les jardins sont payants, on ne peut entrer dans les jardins que 2 fois et par 2 entrées différentes (2 fois, mais pas 2 fois par la même entrée).

Météo & saison :
Été : Chaleur et forte affluence : expérience moins agréable. Penser aux fontaines gratuites pour remplir sa gourde et aux îlots de fraîcheur.
Automne/hiver (novembre-février, par beau temps) : les conditions optimales pour votre visite (programmation riche, moins d’affluence, plus d’expositions).
Pour les franciliens : recommander le château + le Trianon de septembre à mars, et les jardins d’avril à octobre (printemps particulièrement agréable).

En été ou en cas de forte chaleur, ne pas oublier lunettes de soleil et chapeaux / casquettes, gourdes - des points d’eau permettent de les remplir.
Si la période le requiert, rappeler la différence entre Grandes Eaux et Jardins Musicaux.
Vérifier les horaires de fermeture des jardins (informer qu’en haute saison, les samedis de juin à septembre et certains autres jours, les jardins ferment de manière anticipée, à 17h30)

Les weekends d’été, faire la promotion des Grandes Eaux Nocturnes.
Les jours de Grandes Eaux Nocturnes, les jardins ferment à 17h30 avant de rouvrir à 20h pour les grandes eaux nocturnes.
Entre les 2, on peut faire la VR ou la Sérénade Royale puis aller dîner en ville ou aller dans le Parc.
La pluie ou d’autres intempéries n’engendrent pas l’annulation de l’événement.
Encourager les visites les mercredis, jeudi et vendredis jours de moindre affluence.
Si la météo le permet, encourager les services dans le parc avec les vélos, les barques et les balades au bord du canal.
D’une manière générale, il faut orienter les réponses vers les visites guidées, ateliers familles, expositions, nouveaux espaces.
En effet, pour des personnes qui sont déjà venues, il faut leur dire qu’il y a de nouvelles choses depuis la dernière fois. Le château est
parfois perçu comme immobile et figé, or, on peut revenir et voir de nouvelles choses : Trianon, galerie des carrosses et/ou sculptures,
salle du jeu de paume, exposition, ouvertures exceptionnelles (salle du Congrès, Trianon sous bois, …), …


INFORMATIONS COMPLEMENTAIRES

Le Château
Le château est ouvert, tous les jours sauf les lundis.
Horaires : 9h - 18h30
Dernière admission : 17h45
Fermeture des caisses : 17h30

Le domaine de Trianon
Ouvert tous les jours, sauf les lundis.
Horaires : 12h - 18h30
Dernière admission : 17h45
Fermeture des caisses : 17h45
Les jardins ferment à 18h30 (évacuation à partir de 18h).

Le domaine de Marly
Ouvert aux piétons tous les jours
Accès par la porte du Bourg, la grille Deux portes, la grille Royale, la grille Cœur Volant, la porte du Roi et la porte du Stade de 7h30 à 19h30 (dernière admission à 19h), du 1er avril au 31 octobre, et de 8h à 17h30 du 1er novembre au 31 mars.

Les Jardins
Ouverts tous les jours, de 7h à 20h30
Dernier accès : 19h sauf météo exceptionnelle (neige, vents violents…).
Fermeture anticipée des jardins à 17h30 à l’occasion des Grandes Eaux Nocturnes, les samedis du 7 juin au 20 septembre, ainsi que les 26, 28, 29, 30 et 31 octobre.
Accès piétons par la cour d’honneur ou par le Parc (grilles de la Petite Venise, de la Ménagerie et de Neptune) de 7h à 20h30 et par la grille du Dragon de 7h à 19h30 (dernier accès 19h).

La salle du Jeu de Paume
La salle du Jeu de Paume sera exceptionnellement fermée au public toute la journée du 19 août.
La salle du Jeu de Paume est ouverte tous les jours, sauf les lundis.
Horaires : 12h30 - 18h30
Dernière admission : 17h45
Accès : Gratuit


Le Parc
Ouvert tous les jours, de 7h à 20h30
Dernier accès : 19h45
(sauf météo exceptionnelle : neige, vents violents…)

Accès piéton par :

•	la grille de la Reine (7h - 20h30, dernier accès à 19h45)
•	la grille des Matelots (7h - 19h30, dernier accès à 19h00)
•	la grille Saint-Antoine (7h - 19h30, dernier accès à 19h00)
•	la grille d’Honneur (7h - 19h30, dernier accès à 19h)
•	la grille de l’Étoile Royale (7h - 19h30, dernier accès à 19h)
•	la grille de la Chapelle (9h - 17h30, dernier accès 17h30, sauf les lundis)


Accès véhicule par :

•	la grille de la Reine (9h - dernier accès caisse 17h50)
•	la grille Saint-Antoine (9h - dernier accès caisse 17h50, uniquement les week-ends et jours fériés)


La galerie des Carrosses
Ouverte les samedis, dimanches et jours fériés, sauf les lundis.
Ouverture exceptionnelle le vendredi 15 août
Horaires : 12h30 - 18h30
Dernière admission : 17h45
Accès : Gratuit

La galerie des Sculptures et des Moulages
Ouverte les samedis, dimanches et jours fériés, sauf les lundis.
Ouverture exceptionnelle le vendredi 15 août
Horaires : 12h30 - 18h30
Dernière admission : 17h45
Accès : Gratuit

""",




  
]